# Generated by Django 2.0.6 on 2019-03-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnewusermodel',
            old_name='password1',
            new_name='confirmPassword',
        ),
        migrations.RenameField(
            model_name='createnewusermodel',
            old_name='password2',
            new_name='password',
        ),
    ]
