# Generated by Django 2.0.6 on 2019-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0002_auto_20190306_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewusermodel',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
